In [1]:
from graph_tool.all import *
from makegraph import make_graph
from makegraph import graph_to_matrix
from numpy.random import randint
from numpy.random import random
from numpy.random import *
import numpy as np

In [2]:
g=make_graph(1000,'Japan')

In [3]:
#states
S = [1, 1, 1, 1]          # SUSCEPTIBLE

I = [0, 0, 0, 1]          # INFECTED

R = [0.5, 0.5, 0.5, 1.]   # RECOVERED

Sv = [0, 0, 1, 1]         # SUSCEPTIBLE + VACCINATED

Iv = [0.2,0.2,0.5,1]      # INFECTED + VACCINATED

D = [0.8, 0, 0, 0.6]      # DEAD

In [4]:
print(graph_to_matrix(g))

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [5]:
#print(scount)