In [9]:
from graph_tool.all import *
from makegraph import make_graph
from makegraph import graph_to_matrix
from numpy.random import randint
from numpy.random import random
from numpy.random import *
import numpy as np

In [15]:
    if 1 ==1:
        size = 103
        g = Graph(directed=False)
    
        # insert random vertices (nodes)
        g.add_vertex(size)
    
        # insert some random links
        for s,t in zip(randint(0, size, 2*size), randint(0, size, 2*size)):
            g.add_edge(g.vertex(s), g.vertex(t))
    else:
         g=graph_tool.generation.price_network(101, m=5, c=None, gamma=1, directed=False,seed_graph=None)

In [16]:
g

<Graph object, undirected, with 103 vertices and 206 edges, at 0x7f423a971c40>

In [3]:
#states
S = [1, 1, 1, 1]          # SUSCEPTIBLE

I = [0, 0, 0, 1]          # INFECTED

R = [0.5, 0.5, 0.5, 1.]   # RECOVERED

Sv = [0, 0, 1, 1]         # SUSCEPTIBLE + VACCINATED

Iv = [0.2,0.2,0.5,1]      # INFECTED + VACCINATED

D = [0.8, 0, 0, 0.6]      # DEAD

In [4]:
print(graph_to_matrix(g))

[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [5]:
#print(scount)